### ISSUE TITLE
Love your work - I found this method a bit more elegant with ALB's

### ISSUE THREAD

**Issue by jellis** [geerlingguy/ansible-for-kubernetes#110]
Hey Jeff,

Your work with Ansible absolutely rocks. I've been doing govt work and whatnot for the last few years and enjoy talking people around to using Ansible for lots of hacky things because it helps to build out a standardised interface (user API?) for getting things done across real computers, VM's, cloud providers etc.

I was recently going through the benefits of using Ansible/Jinja templates for K8S deployments when compared to helm and kustomize - in my opinion, it's hands down the simplest way to inject variables into manifests. Below is some code I wrote to extract the LB DNS endpoint which removes an extra lookup that you're doing below.

https://github.com/geerlingguy/ansible-for-kubernetes/blob/54a03d7c4911e099cacf92df0d1afb7a44a9b569/cluster-aws-eks/deploy.yml#L39

```
- name: get the AWS DNS address for the LB
  kubernetes.core.k8s_info:
    kind: Ingress
    namespace: "{{ app_environment }}"
    name: "myapp-{{ app_environment }}-{{ aws_environment }}-ingress"
  register: myapp_alb_deployment_status
  until: myapp_alb_deployment_status.resources[0].status.loadBalancer.ingress[0].hostname is defined
  retries: 20
  delay: 3
```

Keep up the great work. Loving your YT stuff, too.
