### ISSUE TITLE
Possibly wrong description in task

### ISSUE THREAD

**Issue by qmacro** [geerlingguy/ansible-for-kubernetes#28]
In Ch.3 section "Running a local container registry" (very interesting section btw!) there's a task that looks like this:

```
tasks:
 - name: Ensure the Docker registry container is present.
   docker_image:
     name: '{{ registry_image }}'
     source: pull
```

But I think the name should be "Ensure the Docker registry **image** is present."
