### ISSUE TITLE
EKS example needs update to VPS subnet IP settings

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-for-kubernetes#52]
For more details, see [Upcoming Changes to IP Assignment for EKS Managed Node Groups](https://aws.amazon.com/blogs/containers/upcoming-changes-to-ip-assignment-for-eks-managed-node-groups/).

It seems like I would just need to add the property `MapPublicIpOnLaunch: true` to all the subnets in the `vpc.yml` template:

```
  Subnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone:
        Fn::Sub: '${Region}a'
      CidrBlock: 172.16.0.0/18
      # This is the new setting:
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: eks-example-a
```
