### ISSUE TITLE
Kubernetes Not Running After Reboot

### ISSUE THREAD

**Issue by wstrater** [geerlingguy/ansible-for-kubernetes#63]
I built newly provisioned Ubuntu 18.04 machines using `geerlingguy.security`, `geerlingguy.swap`, `geerlingguy.docker` and `geerlingguy.kubernetes`. 

I am able to access Kubernetes until I reboot the machine. It appears that Kubernetes does not restart but Docker does. I run `ps aux | grep kube | grep -v kube | wc -l` after reboot and get 0 entries. After I re-run the playbook there are 7 entries and Kubernetes is accessible.

The only thing that changes are the swap. They change even if I re-run the playbook without rebooting.

```
TASK [geerlingguy.swap : Disable swap (if configured).] *********************************************************************************************************
changed: [k8sworker1]
changed: [k8scontroller]
changed: [k8sworker2]
```

Here are my basic variables.

```
docker_install_compose: false
docker_users:
  - wes

swap_file_state: absent
swap_file_path: /dev/mapper/packer--debian--10--amd64--vg-swap_1

kubernetes_version: '1.18'
kubernetes_allow_pods_on_master: false
kubernetes_apiserver_advertise_address: 192.168.1.210
kubernetes_kubelet_extra_args: '--node-ip={{ ansible_host }}'
```

Here is the basic playbook based on your Ansible for Kubernetes book. I have some other tasks after the roles to copy the generated kube config file.

```
  roles:
    - role: geerlingguy.security
      tags: [ docker, kubernetes ]
    - role: geerlingguy.swap
      tags: [ docker, kubernetes ]
    - role: geerlingguy.docker
      tags: [ docker, kubernetes, docker_only ]
    - role: geerlingguy.kubernetes
      tags: [ kubernetes, kubernetes_only ]
```

Not sure the version of the roles but I downloaded them a few days ago, 8/14/20.

This is pretty consistent behavior.

Wes.
