### ISSUE TITLE
Ch4 (cluster-local-vms) p79 - geerlingguy.docker role fails due to stale apt cache

### ISSUE THREAD

**Issue by jim-whiteside** [geerlingguy/ansible-for-kubernetes#94]
Failure at `geerlingguy.docker : Ensure dependencies are installed.` 

> Failed to fetch http://security.debian.org/debian-security/pool/updates/main/a/apt/apt-transport-https_1.8.2.1_all.deb  404  Not Found [IP: 151.101.62.132 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

A similar issue was reported in https://github.com/geerlingguy/ansible-role-docker/pull/118 - proposed solution was "controlling apt caches in the playbook that uses the role / outside the role."

So I add the following pre_task to main.yml:

```
  pre_tasks:
    - name: Run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600
```
